use buildx, make default and nginx images

diff --git a/hooks/env b/hooks/env
--- a/hooks/env
+++ b/hooks/env
@@ -28,20 +28,53 @@ DOCKER_FILE='Dockerfile'
 . "build.conf" || { echo 'No build.conf!'; exit 1; }
 
 ## handling writing and printing of parameters
-#	del_param       <key>
-#	add_param       <value> <key>
+#	del_param       <param>
+#	add_param       <value> <param>
 #	print_param     <value> <desc>
-#	add_print_param <value> <key> <desc>
-del_param() { sed "/${1}/d" -i "${CONFIG_YAML}"; }
+#	add_print_param <value> <param> <desc>
+del_param() { sed "/^${1}:/d" -i "${CONFIG_YAML}"; }
 add_param () {
-	key="${2}"
+	local value
 	value="$(echo "${1}" | xargs)"
-	del_param "${key}"
-	echo "${key}: ${value}" >> "${CONFIG_YAML}"
-	declare -g "${key}=${value}"
+	del_param "${2}"
+	echo "${2}: ${value}" >> "${CONFIG_YAML}"
+	declare -g "${2}=${value}"
 }
-print_param () { printf '%-20s %-8s\n' "${2}" "${1}"; }
+print_param () { printf '%-40s %-8s\n' "${2}" "${1}"; }
 add_print_param () { add_param "${1}" "${2}"; print_param "${1}" "${3:-${2}}"; }
+
+# only execute code to determine the parameter if it's unset, otherwise use the
+# existing set value
+#
+# these have arguments in different positions than the add/print_param functions
+#
+#	eval_param_ifn       <param> <command>
+#	eval_print_param_ifn <param> <desc> <command>
+eval_param_ifn () {
+	local param
+	local command
+	local value
+
+	param="${1}"
+	IFS=' ' read -a command <<< "${2}"
+
+	[ ! -z "${DEBUG+set}" ] \
+		&& >&2 echo "eval_param_ifn command: ${command[*]}"
+
+	[ -z "${!param}" ] \
+		&& value="$(eval "${command[*]}")" \
+		|| value="${!param}"
+
+	add_param "${value}" "${param}"
+}
+
+eval_print_param_ifn () {
+	local desc
+	[ ! -z "${3}" ] && desc="${2}"
+
+	eval_param_ifn "${1}" "${3:-${2}}"
+	print_param "${!1}" "${desc:-${1}}"
+}
 
 ## curl the provided URL, handle errors and cache
 # get_url <URL>
@@ -52,16 +85,16 @@ get_url () {
 	cache_file="${DATA_DIR}/$(echo "${1}" | md5sum | cut -d' ' -f1)"
 
 	if [ -f "${cache_file}" ] && [ "$(( $(date +"%s") - $(date -r "${cache_file}" +"%s") ))" -lt "${CACHE_EXPIRY}" ]; then
-#		>&2 echo "Using cache: ${cache_file}"
 		cat "${cache_file}"
 	else
-#		>&2 echo "Downloading: ${1}"
 		page_data="$(curl -sL -w "%{http_code}\n" "${1}")"
 		http_code="${page_data:(-3)}"
 		if [ "${http_code}" = "200" ]; then
 			echo "${page_data%???}" | tee "${cache_file}"
 		else
-			echo "HTTP Error: ${http_code}"
+			>&2 echo "URL: ${1}"
+			>&2 echo "cache file: $(echo "${1}" | md5sum | cut -d' ' -f1)"
+			>&2 echo "HTTP Error: ${http_code}"
 			return 1
 		fi
 	fi
@@ -73,18 +106,32 @@ git_api_data () {	get_url "https://api.github.com/repos/${1}/${2}"; }
 # git_api_element <repo> <request> <element>
 git_api_element () { git_api_data "${1}" "${2}" | sed -En 's|.*"'"${3}"'"\W+"([^"]+)".*|\1|p'; }
 
+# git_repo_releases <repo> (<element>)
+git_repo_releases () { git_api_element "${1}" 'releases' "${2:-tag_name}" | sort -uV; }
+
 # git_latest_release <repo> (<element>)
 git_latest_release () { git_api_element "${1}" 'releases/latest' "${2:-tag_name}"; }
+# git_latest_release <repo>
+# git_latest_release () {	git_repo_releases "${1}" | tail -n1; }
+
+# git_repo_tags <repo> (<element>)
+git_repo_tags () { git_api_element "${1}" 'tags' "${2:-name}" | sort -uV; }
+
+# git_latest_tag <repo> (<element>)
+# git_latest_tag () {	git_api_element "${1}" 'tags' "${2:-name}" | sort -uV | tail -n1; }
+# git_latest_tag <repo>
+git_latest_tag () {	git_repo_tags "${1}" | tail -n1; }
 
 # alpine_package_version <package> <alpine version> <repos>
 #
 # <repos> is a list, defaults to "main community"
 #
 alpine_package_version () {
+	local alpine_version
 	alpine_version="$(echo "${2}" | awk -F \. '{print $1"."$2}')"
-	repos="${3:-main community}"
+	local repos && repos="${3:-main community}"
 
-	packages=''
+	local package && packages=''
 	for repo in ${repos}; do
 		packages="$(printf '%s\n%s' \
 			"$(get_url "https://dl-cdn.alpinelinux.org/alpine/v${alpine_version}/${repo}/x86_64/" | grep -oP "^<a.*>\K[^<]*apk(?=<)")" \
@@ -98,6 +145,23 @@ alpine_package_version () {
 	echo "${packages}" | grep -oP "^${1}-\K[0-9.]*"
 }
 
+# debian_package_version <package> <debian release>
+#
+debian_package_version () {
+	local package && package="${1}"
+	local debian_release && debian_release="${2}"
+
+	if [ -z "${package}" ] || [ -z "${debian_release}" ]; then
+		return
+	fi
+
+	# either of these works
+#	package_version="$(get_url "https://sources.debian.org/api/src/${package}/" | grep -oP "\"suites\"[^}]*${debian_release}\"[^}]*version\D*\K[0-9\.\-]*")"
+	package_version="$(get_url "https://sources.debian.org/api/src/nginx/${debian_release}/" | grep -oP 'version"\:"\K([^\"]*)' | cut -d'+' -f1)"
+
+	echo "${package_version}"
+}
+
 # pypi_api_XXXX <project>
 pypi_api_data () {	get_url "https://pypi.org/simple/${1}"; }
 pypi_api_versions () { pypi_api_data "${1}" | grep -oP "(?<=${1}-)[0-9.]{4,}(?=.tar.gz)" | sort -uV; }
@@ -106,6 +170,9 @@ pypi_api_latest_version () { pypi_api_versions "${1}" | tail -n1; }
 # py_musl_wheel_XXXX <wheel string>
 py_musl_wheel_versions () { docker_api_repo_tags "${WHEEL_REPO}" | grep -oP "${1}\K([0-9.]+)(?=-py)" | sort -uV; }
 py_musl_wheel_latest () { py_musl_wheel_versions "${1}" | tail -n1; }
+
+parse_version_major () { echo "${1}" | awk -F \. '{print $1}'; }
+parse_version_minor () { echo "${1}" | awk -F \. '{print $1"."$2}'; }
 
 #
 # py_requireed_vesion() and python_get_module_from_string() needs a refactor,
@@ -279,7 +346,7 @@ docker_container_contents () {
 	local output_dir &&	output_dir="${2:-./}"
 	local tar_args && tar_args="${3}"
 
-	echo "Importing: ${import_image}"
+	echo "Importing files from ${import_image} to ${output_dir}"
 
 	[ -n "${NOOP+set}" ] && [ -z "${WHEELS_FORCE_PULL+set}" ] && echo 'Status: [NOOP]' && return
 
